// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_snMec8J9MxGMHUURwI63491GK4eyfY',
    appId: '1:206024295635:web:97c0477ea746deac7f4026',
    messagingSenderId: '206024295635',
    projectId: 'grand-chess-d7983',
    authDomain: 'grand-chess-d7983.firebaseapp.com',
    storageBucket: 'grand-chess-d7983.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEaVL3CxpbI3I7t4e8oQO3ke4CODKwYNM',
    appId: '1:206024295635:android:e306a39650e3d7cf7f4026',
    messagingSenderId: '206024295635',
    projectId: 'grand-chess-d7983',
    storageBucket: 'grand-chess-d7983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpKq8Jaf4MfkSq-O0K2GG_4j8gYVlH1Y',
    appId: '1:206024295635:ios:c9f326666efebde57f4026',
    messagingSenderId: '206024295635',
    projectId: 'grand-chess-d7983',
    storageBucket: 'grand-chess-d7983.firebasestorage.app',
    iosBundleId: 'com.example.grandChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpKq8Jaf4MfkSq-O0K2GG_4j8gYVlH1Y',
    appId: '1:206024295635:ios:c9f326666efebde57f4026',
    messagingSenderId: '206024295635',
    projectId: 'grand-chess-d7983',
    storageBucket: 'grand-chess-d7983.firebasestorage.app',
    iosBundleId: 'com.example.grandChess',
  );
}
